name: TruffleHog - Scan For Secrets
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
  scan_for_secrets:
    runs-on: ubuntu-latest
     # Needed for GitHubâ€™s dependency-submission API later
    permissions:
      contents: read
      id-token: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: TruffleHog Scan
        if: github.event_name == 'pull_request'
        timeout-minutes: 5
        uses: trufflesecurity/trufflehog@main
        continue-on-error: true
        with:
          path: ./
          base: "${{ github.event.pull_request.base.sha }}"
          head: "${{ github.event.pull_request.head.sha }}"
          extra_args: --debug

      - name: TruffleHog Scan (push / manual)
        if: github.event_name != 'pull_request'
        timeout-minutes: 5
        uses: trufflesecurity/trufflehog@main
        continue-on-error: true
        with:
          path: ./